# Generated by Django 4.2.17 on 2024-12-23 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_added', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('needs_password', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=300, null=True)),
                ('hashed_password', models.CharField(blank=True, max_length=500, null=True)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rota', models.CharField(max_length=100)),
                ('is_login', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.website')),
            ],
        ),
    ]
