# Generated by Django 4.2.17 on 2024-12-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='number',
            field=models.CharField(default=5511951266317, max_length=30),
            preserve_default=False,
        ),
    ]
